name             'ar_api'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ar_api'
long_description 'Installs/Configures ar_api'
version          '0.1.0'
